@extends('admin.layout')

@section('title', 'Activity Calendar - Sapphire Hotel Management')
@section('header', 'Activity Calendar')

@section('content')
<div class="mb-6 flex justify-between items-center">
    <h2 class="text-2xl font-bold text-gray-800">Activity Calendar</h2>
    <div class="flex space-x-2">
        <a href="{{ route('admin.activities.bookings.index') }}" class="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition">
            <i class="fas fa-list mr-2"></i>List View
        </a>
        <a href="{{ route('admin.activities.bookings.create') }}" class="bg-green-600 text-white px-4 py-2 rounded-lg hover:bg-green-700 transition">
            <i class="fas fa-plus mr-2"></i>New Booking
        </a>
    </div>
</div>

<!-- Filters and Navigation -->
<div class="bg-white rounded-lg shadow p-4 mb-6">
    <div class="flex flex-wrap items-center justify-between gap-4">
        <div class="flex items-center space-x-4">
            <select id="activityFilter" class="border rounded px-3 py-2">
                <option value="">All Activities</option>
                @foreach($activities as $activity)
                    <option value="{{ $activity->id }}">{{ $activity->name }}</option>
                @endforeach
            </select>
            
            <div class="flex items-center space-x-2">
                <button id="prevMonth" class="p-2 hover:bg-gray-100 rounded">
                    <i class="fas fa-chevron-left"></i>
                </button>
                <span id="currentMonth" class="font-medium text-lg">{{ $startDate->format('F Y') }}</span>
                <button id="nextMonth" class="p-2 hover:bg-gray-100 rounded">
                    <i class="fas fa-chevron-right"></i>
                </button>
            </div>
        </div>
        
        <div class="flex items-center space-x-4">
            <button id="todayBtn" class="bg-gray-600 text-white px-3 py-1 rounded hover:bg-gray-700 transition">
                Today
            </button>
            <div class="flex items-center space-x-2 text-sm">
                <div class="flex items-center">
                    <div class="w-3 h-3 bg-yellow-500 rounded-full mr-1"></div>
                    <span>Pending</span>
                </div>
                <div class="flex items-center">
                    <div class="w-3 h-3 bg-green-500 rounded-full mr-1"></div>
                    <span>Confirmed</span>
                </div>
                <div class="flex items-center">
                    <div class="w-3 h-3 bg-blue-500 rounded-full mr-1"></div>
                    <span>Completed</span>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Calendar Grid -->
<div class="bg-white rounded-lg shadow overflow-hidden">
    <div class="grid grid-cols-7 bg-gray-50">
        <div class="p-3 text-center font-medium text-gray-700 border-r">Sunday</div>
        <div class="p-3 text-center font-medium text-gray-700 border-r">Monday</div>
        <div class="p-3 text-center font-medium text-gray-700 border-r">Tuesday</div>
        <div class="p-3 text-center font-medium text-gray-700 border-r">Wednesday</div>
        <div class="p-3 text-center font-medium text-gray-700 border-r">Thursday</div>
        <div class="p-3 text-center font-medium text-gray-700 border-r">Friday</div>
        <div class="p-3 text-center font-medium text-gray-700">Saturday</div>
    </div>
    
    <div id="calendarGrid" class="grid grid-cols-7">
        <!-- Calendar days will be generated by JavaScript -->
    </div>
</div>

<!-- Activity Details Modal -->
<div id="activityModal" class="fixed inset-0 bg-black bg-opacity-50 hidden z-50 flex items-center justify-center">
    <div class="bg-white rounded-lg max-w-2xl w-full mx-4 max-h-[80vh] overflow-y-auto">
        <div class="p-6">
            <div class="flex justify-between items-center mb-4">
                <h3 class="text-xl font-semibold">Activity Details</h3>
                <button onclick="closeModal()" class="text-gray-500 hover:text-gray-700">
                    <i class="fas fa-times"></i>
                </button>
            </div>
            <div id="modalContent">
                <!-- Activity details will be loaded here -->
            </div>
        </div>
    </div>
</div>

<script>
let currentMonth = '{{ $startDate->format("Y-m") }}';
let bookings = {!! $bookings->map(function($booking) {
    return [
        'id' => $booking->id,
        'activity_name' => $booking->activity->name,
        'activity_type' => $booking->activity->type,
        'user_name' => $booking->user->name,
        'scheduled_time' => $booking->scheduled_time->format('Y-m-d H:i:s'),
        'participants' => $booking->participants,
        'status' => $booking->status,
        'total_price' => $booking->total_price
    ];
})->toJson() !!};

function generateCalendar(month) {
    const date = new Date(month + '-01');
    const year = date.getFullYear();
    const monthIndex = date.getMonth();
    
    // Update month display
    const monthNames = ['January', 'February', 'March', 'April', 'May', 'June',
                       'July', 'August', 'September', 'October', 'November', 'December'];
    document.getElementById('currentMonth').textContent = `${monthNames[monthIndex]} ${year}`;
    
    // Get first day of month and number of days
    const firstDay = new Date(year, monthIndex, 1).getDay();
    const daysInMonth = new Date(year, monthIndex + 1, 0).getDate();
    
    // Clear calendar
    const calendarGrid = document.getElementById('calendarGrid');
    calendarGrid.innerHTML = '';
    
    // Add empty cells for days before month starts
    for (let i = 0; i < firstDay; i++) {
        calendarGrid.innerHTML += '<div class="border-r border-b p-2 h-24 bg-gray-50"></div>';
    }
    
    // Add days of the month
    for (let day = 1; day <= daysInMonth; day++) {
        const dateStr = `${year}-${String(monthIndex + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
        const dayBookings = bookings.filter(booking => 
            booking.scheduled_time.startsWith(dateStr)
        );
        
        const isToday = new Date().toDateString() === new Date(year, monthIndex, day).toDateString();
        
        let dayHtml = `<div class="border-r border-b p-2 h-24 ${isToday ? 'bg-blue-50' : ''} relative overflow-hidden">`;
        dayHtml += `<div class="font-medium text-sm mb-1">${day}</div>`;
        
        if (dayBookings.length > 0) {
            const activityFilter = document.getElementById('activityFilter').value;
            const filteredBookings = activityFilter 
                ? dayBookings.filter(booking => booking.activity_id == activityFilter)
                : dayBookings;
            
            filteredBookings.slice(0, 3).forEach(booking => {
                const statusColors = {
                    'pending': 'bg-yellow-500',
                    'confirmed': 'bg-green-500',
                    'completed': 'bg-blue-500'
                };
                
                dayHtml += `
                    <div class="text-xs mb-1 cursor-pointer hover:opacity-80" 
                         onclick="showActivityDetails(${JSON.stringify(booking).replace(/"/g, '&quot;')})">
                        <div class="flex items-center">
                            <div class="w-2 h-2 ${statusColors[booking.status]} rounded-full mr-1"></div>
                            <span class="truncate">${booking.activity_name}</span>
                        </div>
                        <div class="text-gray-500">${booking.participants} ppl</div>
                    </div>
                `;
            });
            
            if (filteredBookings.length > 3) {
                dayHtml += `<div class="text-xs text-gray-500">+${filteredBookings.length - 3} more</div>`;
            }
        }
        
        dayHtml += '</div>';
        calendarGrid.innerHTML += dayHtml;
    }
    
    // Add empty cells for remaining days
    const totalCells = calendarGrid.children.length;
    const remainingCells = 42 - totalCells; // 6 rows × 7 days
    for (let i = 0; i < remainingCells; i++) {
        calendarGrid.innerHTML += '<div class="border-r border-b p-2 h-24 bg-gray-50"></div>';
    }
}

function showActivityDetails(booking) {
    const modal = document.getElementById('activityModal');
    const content = document.getElementById('modalContent');
    
    const statusColors = {
        'pending': 'bg-yellow-100 text-yellow-800',
        'confirmed': 'bg-green-100 text-green-800',
        'completed': 'bg-blue-100 text-blue-800'
    };
    
    content.innerHTML = `
        <div class="space-y-4">
            <div class="grid grid-cols-2 gap-4">
                <div>
                    <span class="text-sm text-gray-500">Activity</span>
                    <p class="font-medium">${booking.activity_name}</p>
                </div>
                <div>
                    <span class="text-sm text-gray-500">Type</span>
                    <p class="font-medium">${booking.activity_type}</p>
                </div>
                <div>
                    <span class="text-sm text-gray-500">Guest</span>
                    <p class="font-medium">${booking.user_name}</p>
                </div>
                <div>
                    <span class="text-sm text-gray-500">Participants</span>
                    <p class="font-medium">${booking.participants}</p>
                </div>
                <div>
                    <span class="text-sm text-gray-500">Scheduled Time</span>
                    <p class="font-medium">${new Date(booking.scheduled_time).toLocaleString()}</p>
                </div>
                <div>
                    <span class="text-sm text-gray-500">Amount</span>
                    <p class="font-medium">$${booking.total_price.toFixed(2)}</p>
                </div>
            </div>
            <div>
                <span class="text-sm text-gray-500">Status</span>
                <div class="mt-1">
                    <span class="px-3 py-1 inline-flex text-sm leading-5 font-semibold rounded-full ${statusColors[booking.status]}">
                        ${booking.status.charAt(0).toUpperCase() + booking.status.slice(1)}
                    </span>
                </div>
            </div>
            <div class="flex justify-end space-x-2 pt-4 border-t">
                <button onclick="closeModal()" class="px-4 py-2 border border-gray-300 rounded-lg hover:bg-gray-50">
                    Close
                </button>
                <a href="/admin/activities/bookings/${booking.id}" class="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700">
                    View Details
                </a>
            </div>
        </div>
    `;
    
    modal.classList.remove('hidden');
}

function closeModal() {
    document.getElementById('activityModal').classList.add('hidden');
}

// Event listeners
document.getElementById('prevMonth').addEventListener('click', function() {
    const date = new Date(currentMonth + '-01');
    date.setMonth(date.getMonth() - 1);
    currentMonth = date.toISOString().slice(0, 7);
    generateCalendar(currentMonth);
});

document.getElementById('nextMonth').addEventListener('click', function() {
    const date = new Date(currentMonth + '-01');
    date.setMonth(date.getMonth() + 1);
    currentMonth = date.toISOString().slice(0, 7);
    generateCalendar(currentMonth);
});

document.getElementById('todayBtn').addEventListener('click', function() {
    const today = new Date();
    currentMonth = today.toISOString().slice(0, 7);
    generateCalendar(currentMonth);
});

document.getElementById('activityFilter').addEventListener('change', function() {
    generateCalendar(currentMonth);
});

// Initialize calendar
generateCalendar(currentMonth);
</script>
@endsection
